name: social_login_web
description: Handles Web login in many social networks
version: 2.0.0
homepage: https://github.com/Colossus-Services/social_login_web

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.0.5

dev_dependencies:
  test: ^1.16.7
